#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-concurrentlinkedhashmap
Version  : 1.4
Release  : 1
URL      : https://github.com/ben-manes/concurrentlinkedhashmap/archive/concurrentlinkedhashmap-lru-1.4.tar.gz
Source0  : https://github.com/ben-manes/concurrentlinkedhashmap/archive/concurrentlinkedhashmap-lru-1.4.tar.gz
Source1  : http://repo1.maven.org/maven2/com/googlecode/concurrentlinkedhashmap/concurrentlinkedhashmap-lru/1.4/concurrentlinkedhashmap-lru-1.4.jar
Source2  : http://repo1.maven.org/maven2/com/googlecode/concurrentlinkedhashmap/concurrentlinkedhashmap-lru/1.4/concurrentlinkedhashmap-lru-1.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 GPL-2.0
Requires: mvn-concurrentlinkedhashmap-data = %{version}-%{release}
Requires: mvn-concurrentlinkedhashmap-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
ConcurrentLinkedHashMap
========================
ConcurrentLinkedHashMap is a concurrent, bounded map for use as an in-memory
cache. It is the default caching library in Apache Cassandra and is the
reference algorithm for Google Guava CacheBuilder (formally MapMaker).

%package data
Summary: data components for the mvn-concurrentlinkedhashmap package.
Group: Data

%description data
data components for the mvn-concurrentlinkedhashmap package.


%package license
Summary: license components for the mvn-concurrentlinkedhashmap package.
Group: Default

%description license
license components for the mvn-concurrentlinkedhashmap package.


%prep
%setup -q -n concurrentlinkedhashmap-concurrentlinkedhashmap-lru-1.4

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-concurrentlinkedhashmap
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-concurrentlinkedhashmap/LICENSE
cp NOTICE %{buildroot}/usr/share/package-licenses/mvn-concurrentlinkedhashmap/NOTICE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/googlecode/concurrentlinkedhashmap/concurrentlinkedhashmap-lru/1.4
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/googlecode/concurrentlinkedhashmap/concurrentlinkedhashmap-lru/1.4/concurrentlinkedhashmap-lru-1.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/googlecode/concurrentlinkedhashmap/concurrentlinkedhashmap-lru/1.4
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/googlecode/concurrentlinkedhashmap/concurrentlinkedhashmap-lru/1.4/concurrentlinkedhashmap-lru-1.4.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/googlecode/concurrentlinkedhashmap/concurrentlinkedhashmap-lru/1.4/concurrentlinkedhashmap-lru-1.4.jar
/usr/share/java/.m2/repository/com/googlecode/concurrentlinkedhashmap/concurrentlinkedhashmap-lru/1.4/concurrentlinkedhashmap-lru-1.4.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-concurrentlinkedhashmap/LICENSE
/usr/share/package-licenses/mvn-concurrentlinkedhashmap/NOTICE
